# Generated by Django 5.1.2 on 2024-10-28 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mons_cat', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=200)),
                ('prenoms', models.CharField(max_length=200)),
                ('ville', models.CharField(choices=[('Douala', 'Douala'), ('Yaounde', 'Yaounde'), ('Bafoussam', 'Bafoussam'), ('Edea', 'Edea'), ('Buea', 'Buea'), ('Bameda', 'Bameda'), ('Dschang', 'Dschang')], max_length=200)),
                ('telephone', models.CharField(max_length=15)),
                ('quartier', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_cmde', models.DateTimeField(auto_now_add=True)),
                ('status_cmde', models.CharField(choices=[('Accepter', 'Accepter'), ('Livrer', 'Livrer'), ('Pas_livrer', 'Pas_livrer'), ('Annuler', 'Annuler')], max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('Accepter', 'Accepter'), ('Livrer', 'Livrer'), ('Pas_livrer', 'Pas_livrer'), ('Annuler', 'Annuler')], max_length=200)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_image', models.ImageField(upload_to='media/produit_image')),
                ('noms_prod', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('cmde_min', models.PositiveIntegerField(default=1)),
                ('dure_vie', models.PositiveIntegerField()),
                ('stocke', models.PositiveIntegerField()),
                ('status_produit', models.CharField(choices=[('Nouveaute', 'Nouveaute'), ('Top', 'Top'), ('Promotion', 'Promotion')], max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.produit'),
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.categorie')),
            ],
        ),
    ]
